### ISSUE TITLE
What service is listening on `18.157.68.73:16713`?

### ISSUE THREAD

**Issue by KOLANICH** [mishakorzik/detectvpn#1]

**Comment by mishakorzik** [comment]
according to the specified server, it sends a request to the server and receives from it the result of checking the IP address

**Comment by KOLANICH** [comment]
Are there any docs and source code for it publicly available? I have googled by IP address and port and has found nothing. Also the protocol seems to be partially custom, though likely somehow http-related since `bad request\n` response.

**Comment by mishakorzik** [comment]
Unfortunately, there is no source code because the server uses my personal data, which are used to find out information.

**Comment by KOLANICH** [comment]
Thanks for the info.

1. Why were plain TCP + custom protocol used instead of something TLS-based, like HTTPS or websockets, or plain TLS?
2. What database do you use?

**Comment by mishakorzik** [comment]
This is due to the fact that I don't have servers, so I have to host through ngrok, and to use tls I need a paid subscription. When the war is over, I will have servers and I can do much better. When the war is over I will be very active on github.

I dont use database, i use json.

**Comment by KOLANICH** [comment]
Thanks for the info. 

>I dont use database, i use json.

I meant not the database management system, but the actual dataset. Though I guess JSON may be not the most efficient choice, there are implementations of serializable spatial indexes (usually used in perceptual indexing, such as face recognition, image indexing, plagiarism detection and so on, but any vectors should be OK, if the lib supports the needed metric).

**Comment by mishakorzik** [comment]
ok thanks for the recommendation.

**Comment by KOLANICH** [comment]
From the other PoV IP address is just an integer, and so one doesn't need a spatial index at all.
